version: "3"

services:
  app:
    build:
      context: ./.docker/app
    container_name: payment-app
    image: isaquero/payment-app:dev
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s /entrypoint.sh
    volumes:
      - ./www:/var/www:delegated
    networks:
      - payment-net
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: ./.docker/nginx
    container_name: payment-nginx
    image: isaquero/payment-nginx:dev
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www:delegated
    networks:
      - payment-net
    depends_on:
      - app

  db:
    build:
      context: ./.docker/mysql
    container_name: payment-db
    image: isaquero/payment-db:dev
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment-db
    networks:
      - payment-net

  redis:
    image: redis:alpine
    container_name: payment-redis
    expose:
      - 6379
    networks:
      - payment-net

networks:
  payment-net:
    driver: bridge
